version: "3.7"

services:
  database_pizzaria:
    image: postgres
    container_name: database_pizzaria
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pizzaria
      - POSTGRES_DB=pizzaria
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
